---
- name: Install requred packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: mkdir /var/www/html/images/
  file:
    path: /var/www/html/images/
    state: directory

- name: Symlink vagrant
  file:
    src: /vagrant-volume/http
    dest: /var/www/html/vagrant-http
    state: link
    owner: nobody
    mode: 0777
  when: pxe_env == 'dev'

# - name: Enshure that we have proper permissions for web
#   file:
#     path: /var/www
#     recurse: true
#     owner: nobody
#     mode: 0777
#   when: pxe_env == 'dev'

- name: Enable ip forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: iptables postrouting
  shell: iptables -t nat -A POSTROUTING -o $(ip r | grep default | cut -d ' ' -f 5) -j MASQUERADE
