---

k3os_iso_url_dev: "http://{{ pxe_vagrant_ip }}/vagrant-http/k3os-amd64.iso"
k3os_iso_url_prod: "https://github.com/rancher/k3os/releases/download/v0.22.2-k3s2r0/k3os-amd64.iso"

k3os_iso_url: "{% if pxe_env=='dev' %}{{ k3os_iso_url_dev }}{% else %}{{ k3os_iso_url_prod }}{% endif %}"
