---
- hosts: server
  gather_facts: false
  remote_user: root
  become: true
  roles:
    - prepare

- hosts: server
  gather_facts: true
  become: true
  vars:
    hostname: "kem.q2p.us"
    pxe_vagrant_ip: "192.168.2.2"
  roles:
    - general
    - dhcp
    - tftp
    - nginx
