---
- name: Fail if pxe_env is wrong
  fail:
    msg: "pxe_env is not defined or it's not in dev/stage/prod"
  when: |
    pxe_env is not defined or
    (
      pxe_env != 'dev' and
      pxe_env != 'stage' and
      pxe_env != 'prod'
    )

- name: apt-get update
  raw: DEBIAN_FRONTEND=noninteractive apt-get -y -q update

- name: install python
  raw: test -e /usr/bin/python || (DEBIAN_FRONTEND=noninteractive apt-get install -yq python-minimal python-zipstream)
  register: install_python
  changed_when:
    - install_python.stdout != ""
    - install_python.stdout != "\r\n"
