---
- name: Install requred packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - tftp
    - ipxe

- name: Check k3os iso
  stat:
    path: /vagrant-volume/http/k3os-amd64.iso
  register: stat_k3os_iso
  when: pxe_env == 'dev'

- name: Download k3os iso
  get_url:
    url: "{{ k3os_iso_url_prod }}"
    dest: /vagrant-volume/http/k3os-amd64.iso
  when: |
    stat_k3os_iso.stat is defined and
    stat_k3os_iso.stat.exists == False and
    pxe_env == 'dev'

- name: Check k3os kernel
  stat:
    path: /vagrant-volume/tftpboot/k3os/k3os-vmlinuz-amd64
  register: stat_k3os_kernel

- name: Check k3os initrd
  stat:
    path: /vagrant-volume/tftpboot/k3os/k3os-initrd-amd64
  register: stat_k3os_initrd

- name: Download k3os kernel
  get_url:
    url: "https://github.com/q2p-us/k3os/releases/download/v0.22.2-k3s2r0-grubserial/k3os-vmlinuz-amd64"
    dest: /vagrant-volume/tftpboot/k3os/k3os-vmlinuz-amd64
  when: stat_k3os_kernel.stat.exists == False

- name: Download k3os inird with grub serail patch
  get_url:
    url: "https://github.com/q2p-us/k3os/releases/download/v0.22.2-k3s2r0-grubserial/k3os-initrd-amd64"
    dest: /vagrant-volume/tftpboot/k3os/k3os-initrd-amd64
  when: stat_k3os_initrd.stat.exists == False

- name: Generate and copy syslinux.cfg
  template:
    src: syslinux.cfg.j2
    dest: /vagrant-volume/tftpboot/pxelinux.cfg/default
