---
- name: Install requred packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - tftp
    - p7zip-full

- name: Ensure that necessary dirs are exists
  file:
    path: "/vagrant-volume/{{ item }}"
    state: directory
  with_items:
    - netboot
    - ubuntu

- name: Check netboot.tar.gz
  stat:
    path: /vagrant-volume/netboot.tar.gz
  register: stat_netboot_tar

- name: Download tarball of netboot
  get_url:
    url: "{{ netboot_tar }}"
    dest: /vagrant-volume/netboot.tar.gz
  when: stat_netboot_tar.stat.exists == False

- name: Extract netboot tarball
  unarchive:
    src: /vagrant-volume/netboot.tar.gz
    dest: /vagrant-volume/netboot
    remote_src: yes

- name: Check ubuntu files
  stat:
    path: /vagrant-volume/ubuntu/isolinux
  register: stat_ubuntu
  when: pxe_env == 'dev'

- name: Download ubuntu
  get_url:
    url: "{{ iso }}"
    dest: /vagrant-volume/ubuntu.iso
  when: |
    stat_ubuntu.stat is defined and
    stat_ubuntu.stat.exists == False and
    pxe_env == 'dev'

- name: Extract ubuntu # TODO: replace by mounting or extracting via iso_extract
  shell: 7z x /vagrant-volume/ubuntu.iso -o/vagrant-volume/ubuntu/ && rm -rf /vagrant-volume/ubuntu.iso
  when: |
    stat_ubuntu.stat is defined and
    stat_ubuntu.stat.exists == False and
    pxe_env == 'dev'

- name: Generate and copy syslinux.cfg
  template:
    src: syslinux.cfg.j2
    dest: /vagrant-volume/netboot/ubuntu-installer/amd64/boot-screens/syslinux.cfg
